# Generated by Django 4.0.4 on 2022-06-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_foto_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='date_receita',
            new_name='data_receita',
        ),
    ]
